name: toto_android

description: An Android application for Toto based boards.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  http: ^0.13.6
  intl: ^0.18.1
  video_player: ^2.6.1
  photo_view: ^0.14.0
  dio: ^5.1.2
  file_picker: ^5.3.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
  fonts:
   - family: NotoSans
     fonts:
       - asset: fonts/NotoSans-Bold.ttf
         weight: 700
       - asset: fonts/NotoSans-BoldItalic.ttf
         weight: 700
         style: italic
       - asset: fonts/NotoSans-Italic.ttf
         style: italic
       - asset: fonts/NotoSans-Regular.ttf
       - asset: fonts/NotoSans-SemiBold.ttf
         weight: 300
